name: Build Executables

on:
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }} binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            asset_name: td-lunchmoney-importer-windows-x64.exe
          - os: macos-latest
            asset_name: td-lunchmoney-importer-macos-arm64
          - os: ubuntu-latest
            asset_name: td-lunchmoney-importer-linux-x64

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python 3.9
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1.6.1
      with:
        python_ver: '3.9'
        spec: 'importer.py'
        requirements: 'requirements.txt'
        options: --onefile --name "td-lunchmoney-importer"

    - name: Release
      uses: softprops/action-gh-release@v2.1.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}