name: Build Executables

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            asset_name: td-lunchmoney-importer-windows-x64.exe
          - os: macos-latest
            asset_name: td-lunchmoney-importer-macos-arm64
          - os: ubuntu-latest
            asset_name: td-lunchmoney-importer-linux-x64

    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Python 3.11
      uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1.8.0
      with:
        python_ver: '3.11'
        spec: 'importer.py'
        requirements: 'requirements.txt'
        options: --onefile --name "td-lunchmoney-importer"

    - name: Prepare Release Asset
      run: |
        mkdir -p releases
        mv dist/td-lunchmoney-importer* releases/${{ matrix.asset_name }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2.4.1
      if: github.event_name == 'release'
      with:
        files: releases/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact (for non-release builds)
      uses: actions/upload-artifact@v4.6.2
      if: github.event_name != 'release'
      with:
        name: ${{ matrix.asset_name }}
        path: releases/${{ matrix.asset_name }}