name: Quality Control

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint black isort
        pip install -r requirements.txt

    - name: Analyze with pylint
      run: |
        pylint --disable=C0111,C0301 *.py

    - name: Check requirements.txt
      run: |
        pip check
